import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Favicon from "../public/logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Translate Json File",
  description: "Generated by ps studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(Favicon.src)
  return (
    <html lang="en">
      <link rel="rel icon" href={Favicon.src}/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
